/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kata;

import javax.swing.JOptionPane;

/**
 *
 * @author Pc
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    private Jugadores Jugador1, Jugador2;
    int contador=1;
    int puntoJ1=0;
    int puntoJ2=0;

    public Tablero() {
        initComponents();
        this.Jugador1 = new Jugadores();
        this.Jugador2 = new Jugadores();
        this.Jugador1.setNombre(JOptionPane.showInputDialog(this, "Insertar Nombre del Jugador 1", "Nombre", JOptionPane.QUESTION_MESSAGE));
        this.J1.setText(Jugador1.getNombre());
        this.Jugador2.setNombre(JOptionPane.showInputDialog(this, "Insertar Nombre del Jugador 2", "Nombre", JOptionPane.QUESTION_MESSAGE));
        this.J2.setText(Jugador2.getNombre());
        this.AnotaJ1.setEnabled(false);
        this.AnotaJ2.setEnabled(false);
        this.SigPartida.setEnabled(false);
        this.Fin.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        J1 = new javax.swing.JLabel();
        J2 = new javax.swing.JLabel();
        Text1 = new javax.swing.JTextField();
        Text2 = new javax.swing.JTextField();
        AnotaJ1 = new javax.swing.JButton();
        AnotaJ2 = new javax.swing.JButton();
        Empezar = new javax.swing.JButton();
        SigPartida = new javax.swing.JButton();
        Fin = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        J1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        J1.setText("Jugador 1");

        J2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        J2.setText("Jugador 2");

        AnotaJ1.setText("Anota J1");
        AnotaJ1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnotaJ1MouseClicked(evt);
            }
        });

        AnotaJ2.setText("Anota J2");
        AnotaJ2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnotaJ2MouseClicked(evt);
            }
        });

        Empezar.setText("Empezar Juego");
        Empezar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpezarMouseClicked(evt);
            }
        });

        SigPartida.setText("Siguiente Partida");
        SigPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SigPartidaMouseClicked(evt);
            }
        });

        Fin.setText("Fin del Juego");
        Fin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(AnotaJ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AnotaJ2)
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(J1)
                        .addGap(153, 153, 153)
                        .addComponent(J2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Empezar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SigPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(J1)
                    .addComponent(J2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnotaJ1)
                    .addComponent(AnotaJ2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Empezar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SigPartida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fin)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void anota(Jugadores j){
        j.setScore(j.getScore()+15);
    }
    
    private void EmpezarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpezarMouseClicked
        // TODO add your handling code here:
        this.AnotaJ1.setEnabled(true);
        this.AnotaJ2.setEnabled(true);
    }//GEN-LAST:event_EmpezarMouseClicked

    private void AnotaJ1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnotaJ1MouseClicked
        // TODO add your handling code here:
        anota(Jugador1);
        if (Jugador1.getScore()<=40){
        this.Text1.setText(Jugador1.getScore()+ "");
        } else {
            this.Text1.setText("40");
            Jugador1.setScore(40);
        }
        if (Jugador1.getScore()==40){
        JOptionPane.showMessageDialog(rootPane, Jugador1.getNombre()+" ha ganado la partida " + contador);
        contador++;
        puntoJ1++;
        AnotaJ1.setEnabled(false);
        AnotaJ2.setEnabled(false);
        Empezar.setEnabled(false);
        SigPartida.setEnabled(true);
        Fin.setEnabled(true);
        }
    }//GEN-LAST:event_AnotaJ1MouseClicked

    private void AnotaJ2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnotaJ2MouseClicked
        // TODO add your handling code here:
        anota(Jugador2);
        if (Jugador2.getScore()<=40){
        this.Text2.setText(Jugador2.getScore()+ "");
        } else {
            this.Text2.setText("40");
            Jugador2.setScore(40);
        }
        if (Jugador2.getScore()==40){
        JOptionPane.showMessageDialog(rootPane, Jugador2.getNombre()+" ha ganado la partida " + contador);
        contador++;
        puntoJ2++;
        AnotaJ1.setEnabled(false);
        AnotaJ2.setEnabled(false);
        Empezar.setEnabled(false);
        SigPartida.setEnabled(true);
        Fin.setEnabled(true);
        }
    }//GEN-LAST:event_AnotaJ2MouseClicked

    private void SigPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigPartidaMouseClicked
        AnotaJ1.setEnabled(true);
        AnotaJ2.setEnabled(true);
        Empezar.setEnabled(false);
        this.Text1.setText("");
        this.Text2.setText("");
        Jugador2.setScore(0);
        Jugador1.setScore(0);
    }//GEN-LAST:event_SigPartidaMouseClicked

    private void FinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinMouseClicked
        Empezar.setEnabled(false);
        AnotaJ1.setEnabled(false);
        AnotaJ2.setEnabled(false);
        SigPartida.setEnabled(false);
        if (puntoJ1>puntoJ2){
            JOptionPane.showMessageDialog(rootPane, Jugador1.getNombre()+" ha ganado el juego.");
        } else if (puntoJ1<puntoJ2){
            JOptionPane.showMessageDialog(rootPane, Jugador2.getNombre()+" ha ganado el juego.");
        } else if (puntoJ1==puntoJ2){
            JOptionPane.showMessageDialog(rootPane, "DEUCE!!! \n"
                    + " "+Jugador1.getNombre() +" y "
                    + " "+Jugador2.getNombre() +" han quedado empatados." );
        }
    }//GEN-LAST:event_FinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Tablero llamada = new Tablero();
        llamada.setResizable(false);
        llamada.setTitle("Juego De Tenis, Kata 1");
        llamada.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnotaJ1;
    private javax.swing.JButton AnotaJ2;
    private javax.swing.JButton Empezar;
    private javax.swing.JButton Fin;
    private javax.swing.JLabel J1;
    private javax.swing.JLabel J2;
    private javax.swing.JButton SigPartida;
    private javax.swing.JTextField Text1;
    private javax.swing.JTextField Text2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
